sonar.projectKey=mr-kn-portfolio
sonar.projectName=Mr KN Portfolio
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/coverage/**,**/*.config.js,**/karma.conf.js

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# TypeScript
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json

# Coverage (output from Karma)
sonar.javascript.lcov.reportPaths=coverage/mr-kn-portfolio/lcov.info
sonar.testExecutionReportPaths=coverage/mr-kn-portfolio/sonar-report.xml

# Code quality
sonar.cpd.exclusions=**/*.spec.ts,**/*.module.ts
